const express = require('express')
const app = express()
const dotenv = require('dotenv')
const mongoose = require('mongoose')
const userRoutes = require('./routes/usersRoutes.js')
const uploadroutes = require('./routes/uploadroutes.js')
const cors = require('cors')
dotenv.config()
app.listen(process.env.PORT,()=>{console.log('Server Started')})
mongoose.connect(process.env.localdb).then(()=>{console.log('DB Connected')}).catch(err=>console.log(err))
app.use(cors())
app.use(express.json())

app.use('/api',userRoutes)
app.use('/api',uploadroutes)